services:
  pgvector-db:
    image: pgvector/pgvector:pg17
    container_name: face-recognition-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: faces_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
